- README.md
explain the plan/architecture/potential partner
> Add introduction of the ocp-testing project

- NETWORK.md
More information added, mistake fixed.
> Update and rename network.md to NETWORK.md

- Cases/Benchmark/monitor/cpumonitor/source/cpu_usage.go
Add testcase, source code of the cputotal usage monitor
> Add testcase, source code of the cputotal usage monitor

- Cases/Benchmark/monitor/cpumonitor/source/cpu_usage_breakdown.go
Add testcase go source code for cpu usage breakdown monitor.
> Add testcase go source code for cpu usage breakdown monitor.

- Cases/Benchmark/monitor/cpumonitor/source/cpu_load.go
Add testcase go source code for cpu load monitor.
> Add testcase go source code for cpu load monitor.

- Cases/Benchmark/monitor/cpumonitor/source/cpu_load.go
- Cases/Benchmark/monitor/cpumonitor/source/cpu_per_core_usage.go
- Cases/Benchmark/monitor/cpumonitor/source/cpu_total_usage.go
fomat the output to %.02f in cpuusage testcases
> fomat the output to %.02f in cpuusage testcases

- Cases/Benchmark/monitor/cpumonitor/source/Dockerfile
- Cases/Benchmark/monitor/cpumonitor/source/deadloop.sh
Add Dockerfile and testcpu script in container(deadloop.sh)
> Add Dockerfile and testcpu script in container(deadloop.sh) for cpumonitor testcase

- Cases/Benchmark/monitor/cpumonitor/Benchmark-monitor-cpumonitor-totalusage-docker.json
Add json file for cpu_total_usage monitor.
> Add json file for cpu_total_usage monitor.

- Cases/Benchmark/monitor/memorymonitor/source/memorymonitor.go
> inital memorymonitor

- Cases/Benchmark/monitor/cpumonitor/Benchmark-monitor-cpumonitor-totalusage-docker.json
modify json file for cpu total usage testcase.
> modify json file for cpu total usage testcase.

- Cases/Benchmark/monitor/cpumonitor/Benchmark-monitor-cpumonitor-breakdownusage-docker.json
- Cases/Benchmark/monitor/cpumonitor/Benchmark-monitor-cpumonitor-load-docker.json
- Cases/Benchmark/monitor/cpumonitor/Benchmark-monitor-cpumonitor-overallusage-docker.json
- Cases/Benchmark/monitor/cpumonitor/Benchmark-monitor-cpumonitor-percoreusage-docker.json
Add json file for all cpu monitor testcase.
> Add json file for all cpu monitor testcase.

- Cases/Benchmark/README.md
Add README.md for Benchmark test.
> Add README.md for Benchmark test.

- Cases/Specstest/root_readonly_true/source/config.json
- Cases/Specstest/root_readonly_true/source/root_readonly_true_guset.go
- Cases/Specstest/root_readonly_true/source/root_readonly_true_host.go
testcase:test runc result when Specs.Linuxspec.spec.root.readonly == true
root_readonly_true_host.go: create host reqires, rootfs and config.json for runc
root_readonly_true_guset.go: guest tool on runc.
> Add testcase::test runc result when Specs.Linuxspec.spec.root.readonly == true

- Cases/Specstest/README.md
- Cases/Specstest/root_readonly_true/source/root_readonly_true_host.go
- Cases/Specstest/source/configconvert/config_convert.go
pkg source/configconvert is the pulibc pkg for SPecstest.
> Specstest optimzation, new a public pkg to do convert between specs and config file.

- Cases/Benchmark/monitor/cpumonitor/Benchmark-monitor-cpumonitor-overallusage-docker.json
- Cases/Benchmark/monitor/cpumonitor/source/Dockerfile
- Cases/Benchmark/monitor/cpumonitor/source/deadloop.sh
- Cases/Benchmark/monitor/cpumonitor/source/docker_deploy.sh
- Cases/Benchmark/monitor/cpumonitor/source/host_deploy.sh
Modify the cpu_overall_usage testcase to adapt to the newest test framework.
> Modify the cpu_overall_usage testcase to adapt to the newest test framework.

- Cases/Benchmark/monitor/cpumonitor/Benchmark-monitor-cpumonitor-overallusage-docker.json
Correct class name of container in jsonfile to catch the one in docker_deploy.sh
> Correct class name of container in jsonfile to catch the one in docker_deploy.sh

- engine/scheduler/README.md
Just add to the 'Readme' to remind myself.
> Plan: report auto-generator

- Cases/Benchmark/sysbench/cpu_load/Benchmark-sysbench-cpuload-rkt.json
- Cases/Benchmark/sysbench/file_io/Benchmark-sysbench-fileio-rkt.json
- Cases/Benchmark/sysbench/memory_rw/Benchmark-sysbench-memoryrw-rkt.json
> add sysbench test in Rkt

- Cases/Specstest/README.md
Add specs test scope to README.md
> Add specs test scope to README.md

- Cases/Benchmark/monitor/memorymonitor/Benchmark-monitor-memorymonitor-docker.json
- Cases/Benchmark/monitor/memorymonitor/Benchmark-monitor-memorymonitor-rkt.json
- Cases/Benchmark/monitor/memorymonitor/source/Dockerfile
- Cases/Benchmark/monitor/memorymonitor/source/deadloop.sh
- Cases/Benchmark/monitor/memorymonitor/source/docker_deploy.sh
- Cases/Benchmark/monitor/memorymonitor/source/host_deploy.sh
- Cases/Benchmark/monitor/memorymonitor/source/memorymonitor.go
- Cases/Benchmark/monitor/memorymonitor/source/rkt_deploy.sh
- Cases/Benchmark/monitor/source/adaptor/docker.go
- Cases/Benchmark/monitor/source/adaptor/rkt.go
1.implement the rkt
2.optimize some
3. add json file
> modify memory

- Cases/Specstest/process/source/process_host.go
- Cases/Specstest/root_readonly_false/source/root_readonly_false_host.go
- Cases/Specstest/root_readonly_true/source/root_readonly_true_host.go
- Cases/Specstest/source/hostsetup/host_setup.go
update with changing of OCI/Specs of User.Uid to User.UID.
Change default user of the runc to root, to ensurence the output power.
> Update with oci spec changing

- Cases/Specstest/root_readonly_true/Specstest-root_readonly_true-runc.json
- Cases/Specstest/root_readonly_true/source/root_readonly_true_guest.go
- Cases/Specstest/source/hostsetup/host_setup.go
> Format the output of readonly=true testcase to be a json file.

- Cases/Benchmark/sysbench/cpu_load/Benchmark-sysbench-cpuload-docker.json
- Cases/Benchmark/sysbench/cpu_load/Benchmark-sysbench-cpuload-rkt.json
- Cases/Benchmark/sysbench/file_io/Benchmark-sysbench-fileio-rkt.json
- Cases/Benchmark/sysbench/memory_rw/Benchmark-sysbench-memoryrw-rkt.json
> modify json of rkt-sysbench

- Cases/Benchmark/monitor/cpumonitor/Benchmark-monitor-cpuusage-docker.json
Correct json file description in cpuusage json file.
> Correct json file description in cpuusage json file.

- Cases/Specstest/source/config.json
> Update with changing of the oci/specs, Namespace.devices.

- Cases/Benchmark/monitor/cpumonitor/Benchmark-monitor-cpuusage-rkt.json
- Cases/Specstest/source/config.json
Add cpumonitor support for rkt container.
Fix bug in docker cpumonitor.
> Add cpumonitor support for rkt container.

- Cases/Benchmark/monitor/cpumonitor/Benchmark-monitor-cpuusage-docker.json
Correct json file for testcase: readonly_true.
> Correct json file for testcase: readonly_true.

- Cases/Benchmark/monitor/cpumonitor/Benchmark-monitor-cpuusage-docker.json
Correct json file for cpumonitor.
> Correct json file for cpumonitor.

- Cases/Specstest/platform_linux_amd64/Specstest-paltform_linux_amd64-runc.json
- Cases/Specstest/platform_linux_amd64/source/platform_linux_amd64_host_deploy.go
- Cases/Specstest/platform_linux_amd64/source/test_platform_linux_amd64.go
Format the output of the platform testcase.
Rewrite the test programme.
> Format the output of the platform testcase.

- Cases/Benchmark/monitor/cpumonitor/Benchmark-monitor-cpuusage-docker.json
- Cases/Benchmark/monitor/cpumonitor/source/cpu_usage.go
> Debug update of cpumonitor.

- cases/Benchmark/monitor/dockercpumonitor/source/host_deploy.sh
- cases/Benchmark/monitor/rktcpumonitor/source/host_deploy.sh
> Correct host_deploy.sh.

- cases/Specstest/linux_capabilites/linux_capabilities_SETFCAP_runc.json
- cases/Specstest/linux_capabilites/source/linux_capabilities_SETFCAP_guest.go
- cases/Specstest/linux_capabilites/source/linux_capabilities_SETFCAP_host.go
> add linux-capabilites SETFCAP test

- cases/specstest/platform_linux_amd64/Specstest-paltform_linux_amd64-runc.json
- cases/specstest/platform_linux_amd64/source/test_linux_amd64.sh
Correct platform_linux_amd64 testcase, adapt to framework.
> Correct platform_linux_amd64 testcase, adapt to framework.

- cases/specstest/platform_linux_amd64/Specstest-platform_linux_amd64-runc.json
Correct json file for platform_linux_amd64
> Correct json file for platform_linux_amd64

- cases/specstest/root_readonly_true/Specstest-root_readonly_true-runc.json
Correct json for root_readonly_true.
> Correct json for root_readonly_true.

- cases/specstest/process/Specstest-process-runc.json
- cases/specstest/process/source/process_host.go
- cases/specstest/process/source/test_process.go
- cases/specstest/process/source/test_process.sh
Format output of process testcase to a json file.
> Format output of process testcase to a json file.

- cases/specstest/version_correct/Specstest-version_correct-runc.json
- cases/specstest/version_correct/source/test_version_correct.go
- cases/specstest/version_correct/source/test_version_correct.sh
- cases/specstest/version_correct/source/version_host.go
In specs/version_correct,rewrite with golang, format output to json file, correct json.
> In specs/version_correct,rewrite with golang, format output to json file, correct json.

- cases/specstest/linux_rootfsPropagation/linux_rootfsPropagation_private_runc.json
- cases/specstest/linux_rootfsPropagation/source/linux_rootfsPropagation_private_guest.go
- cases/specstest/linux_rootfsPropagation/source/linux_rootfsPropagation_private_host.go
- cases/specstest/linux_rootfsPropagation/source/linux_rootfsPropagation_private_runcrunner.go
> add linux rootfsPropagation slave test

- cases/specstest/platform_linux_amd64/Specstest-platform_linux_amd64-runc.json
- cases/specstest/process/Specstest-process-runc.json
- cases/specstest/root_readonly_true/Specstest-root_readonly_true-runc.json
Correct jsons for specs testcases.
> Correct jsons for specs testcases.

- cases/network/docker/network-test-iperf-tcp.json
- cases/network/docker/network-test-iperf-udp.json
- cases/network/docker/network-test-ping.json
- cases/network/docker/source/Dockerfile
- cases/network/docker/source/iperf_Client.go
- cases/network/docker/source/iperf_Server.go
- cases/network/docker/source/iperf_test.sh
- cases/network/docker/source/network-config-flannel.sh
- cases/network/docker/source/network-config-pipework.sh
- cases/network/docker/source/network-config-weave.sh
- cases/network/docker/source/ping_test.sh
- cases/network/rkt/iperf-rktfiles/README.md
- cases/network/rkt/iperf-rktfiles/manifest
- cases/network/rkt/iperf-rktfiles/mktree.sh
- cases/network/rkt/iperf-rktfiles/run.sh
- cases/network/rkt/network-test-iperf-tcp.json
- cases/network/rkt/network-test-iperf-udp.json
- cases/network/rkt/network-test-ping.json
- cases/network/rkt/source/iperf-test-rkt.sh
- cases/network/rkt/source/ping-test-rkt.sh
> Adjust the directory structure.

- cases/specstest/root_readonly_true/source/root_readonly_true_host.go
- cases/specstest/source/config.json
- cases/specstest/source/config_newest.json
- cases/specstest/source/configconvert/config_convert.go
- cases/specstest/source/specs/spec.go
- cases/specstest/source/specs/spec_linux.go
- cases/specstest/source/specs/version.go
- cases/specstest/source/specsnewest/spec.go
- cases/specstest/source/specsnewest/spec_linux.go
- cases/specstest/source/specsnewest/version.go
Change using specs in local package, because the framework does not support auto change specs version from github.
> Change using specs in local package, because the framework does not support auto change specs version from github.

- cases/specstest/README.md
- cases/specstest/process/source/process_host.go
Update Readme to guild people to experice specstest temporily.
> Update Readme to guild people to experice specstest temporily.

- cases/specstest/HowTo.md
- cases/specstest/README.md
- cases/specstest/linux_capabilites/source/linux_capabilities_SETFCAP_host.go
- cases/specstest/linux_rootfsPropagation/source/linux_rootfsPropagation_private_host.go
- cases/specstest/mount_fstype/source/mount_fstype_host.go
- cases/specstest/platform_linux_amd64/source/platform_linux_amd64_host_deploy.go
- cases/specstest/root_readonly_false/source/root_readonly_false_host.go
- cases/specstest/version_correct/source/version_host.go
- cases/specstest/version_error/source/version_host.go
Correct all of the specstest cases to call specs using a local pkg.
Modified README.md, and new HowTo.md for specstest.
> Correct all of the specstest cases to call specs using a local pkg, new HowTo.md

- cases/specstest/process/Specstest-process-runc.json
> Correct json file of process.

- cases/specstest/root_readonly_true/Specstest-root_readonly_true-runc.json
> Correct json ,fix run runc path error.

- cases/specstest/process/Specstest-process-runc.json
- cases/specstest/process/source/process_host.go
- cases/specstest/source/config_newest.json
Correct process testcase, adapt to framework, runnable version.
> Correct process testcase, adapt to framework, runnable version.

- cases/specstest/linux_resources/linux_resources_memory_limited.json
- cases/specstest/linux_resources/source/linux_resources_memory_limited_guest.go
- cases/specstest/linux_resources/source/linux_resources_memory_limited_host.go
- cases/specstest/linux_resources/source/linux_resources_memory_limited_runcrunner.go
- cases/specstest/mount_fstype/mount_fstype_support_tmpfs.json
- cases/specstest/mount_fstype/source/mount_fstype_host.go
- cases/specstest/mount_fstype/source/mount_fstype_runcrunner.sh
> modify the mount fstype test case

- cases/specstest/root_readonly_false/Specstest-root_readonly_false-runc.json
Correct output file in json file of readonlyfalse testcase.
> Correct output file in json file of readonlyfalse testcase.

- cases/specstest/root_readonly_false/source/root_readonly_false_host.go
- cases/specstest/root_readonly_true/source/root_readonly_true_host.go
Correct readonlyTrue testcase to fix terminal config err.
> Correct readonly True and false testcase to fix terminal config err.

- cases/specstest/HowTo.md
- cases/specstest/runtestcase.sh
- cases/specstest/startserver.sh
Add script for using specstest for test convenience
Add how to use script for specstest in HowTo.md
>  Add script for using specstest for test convenience

- cases/report/linux_resources_memory_limited.json
- cases/specstest/linux_resources/source/linux_resources_memory_limited_host.go
- cases/specstest/linux_resources/source/linux_resources_memory_limited_runcrunner.go
> fix the linux resource case

- cases/specstest/report/README.md
- cases/specstest/report/linux_capabilities_SETFCAP.json
- cases/specstest/report/linux_rootfsPropagation_private.json
- cases/specstest/report/mount_fstype_out.json
- cases/specstest/report/namespace_out.json
- cases/specstest/report/platform_linux_amd64_out.json
- cases/specstest/report/process_out.json
- cases/specstest/report/readonly_true_out.json
- cases/specstest/report/version_correct_out.json
Add report for testResult of specstest.
> Add report for testResult of specstest.

- cases/specstest/platform_linux_amd64/Specstest-platform_linux_amd64-runc.json
- cases/specstest/platform_linux_amd64/source/platform_linux_amd64_host_deploy.go
Correct platfrom output place, and json bug.
> Correct platfrom output place, and json bug.

- cases/specstest/version_correct/Specstest-version_correct-runc.json
- cases/specstest/version_correct/source/test_version_correct.go
Correct version_correct testcase .
> Correct version_correct testcase .

- cases/network/netns-get/netns-get.json
- cases/network/netns-get/source/netns_get.go
- cases/network/netns-none/netns-none.json
- cases/network/netns-none/source/netns_none.go
> Add new test cases

- cases/network/netns-set/netns-set.json
- cases/network/netns-set/source/netns_set.go
> Add new test case for network namespace.

- .gitignore
> modify the gitignore file

- cases/specstest/namespace/source/ipc.go
- cases/specstest/namespace/source/mount.go
- cases/specstest/namespace/source/namespace.go
- cases/specstest/namespace/source/network.go
- cases/specstest/namespace/source/pid.go
- cases/specstest/namespace/source/testframe.go
- cases/specstest/namespace/source/uts.go
move mashal function from namespace.go to  testframe.go
> move mashal function from namespace.go to  testframe.go

- cases/specstest/adaptor/runc_start.go
- cases/specstest/cases/linuxnamespace/ipc.go
- cases/specstest/cases/linuxnamespace/mount.go
- cases/specstest/cases/linuxnamespace/namespace.go
- cases/specstest/cases/linuxnamespace/network.go
- cases/specstest/cases/linuxnamespace/pid.go
- cases/specstest/cases/linuxnamespace/uts.go
- cases/specstest/hostenv/host_output.go
- cases/specstest/hostenv/host_setup.go
- cases/specstest/utils/configconvert/config_convert.go
Correct import path to github path.
Add public source and first testcase.
> Correct import path to github path. Add public source and first testcase.

- cases/specstest/spec_mount/source/mount.go
- cases/specstest/spec_mount/source/mount_guest.go
- cases/specstest/spec_mount/spec_mount_runc.json
> add new version spec mount test case

- cases/specstest/cases/specversion/test_version_correct.go
- cases/specstest/cases/specversion/test_version_error.go
- cases/specstest/cases/specversion/version.go
- cases/specstest/report/Version_out.json
- cases/specstest/specs.go
Add specs.version testcase in new framework.
> Add specs.version testcase in new framework.

- cases/specstest/cases/specmount/specmount.go
- cases/specstest/cases/specmount/test_mount_tmpfs.go
- cases/specstest/specs.go
> add spec mount test case use the new specstest framword

- cases/specstest/cases/specplatform/paltform.go
- cases/specstest/cases/specplatform/test_platform.go
- cases/specstest/cases/specroot/root.go
- cases/specstest/cases/specroot/test_root_readonly.go
- cases/specstest/manager/casemanager.go
- cases/specstest/report/Mount_out.json
- cases/specstest/report/Platform_out.json
- cases/specstest/report/Root_out.json
- cases/specstest/report/Version_out.json
- cases/specstest/report/namespace_out.json
- cases/specstest/specs.go
Add testcase of specs.root to specstesttool.
> Add testcase of spec.root and spec.platform to specstesttool.

- engine/tools/octest/.gitignore
- engine/tools/octest/config.json
- engine/tools/octest/octest.go
- engine/tools/octest/validate.go
A small tool to test config.json and bundle.
> Add oct test tool.

- engine/tools/octest/octest.go
- engine/tools/octest/validate.go
> Add support for runtime

- engine/tools/octest/layout.go
- engine/tools/octest/layout/config.json
- engine/tools/octest/octest.go
> Adjust some code structures

- cases/specstest/cases/linuxrlimits/linuxrlimits.go
- cases/specstest/cases/linuxrlimits/test_linuxrlimits_RLIMIT_NPROC.go
- cases/specstest/cases/linuxsysctl/linuxsysctl.go
- cases/specstest/cases/linuxsysctl/test_linuxsysctl.go
> add new version linux rlimits test

- cases/specstest/cases/linuxapparmorprofile/linuxapparmorprofile.go
- cases/specstest/cases/linuxapparmorprofile/test_linuxapparmorprofile.go
- cases/specstest/cases/linuxapparmorprofile/testapporprofile
> add linux apparmorprofile test case

- cases/benchmark/README.md
Signed-off-by: Yuan Sun <sunyuan3@huawei.com>
> Remove duplicate description.

- tools/specstest/cases/linuxselinuxlabel/linuxselinuxlabel.go
- tools/specstest/cases/linuxselinuxlabel/test_linuxseliuxlabel.go
- tools/specstest/utils/ouput.go
& correct the path of ouput json file
> add linux selinux process label test case

- tools/specstest/cases/linuxapparmorprofile/linuxapparmorprofile.go
- tools/specstest/cases/linuxapparmorprofile/test_linuxapparmorprofile.go
- tools/specstest/cases/linuxapparmorprofile/testapporprofile
> move linux apparmor test case from branch spectesttool to branch master

- tools/specstest/hostenv/host_runc.go
Enable detech the runc, judge to download runc or not, and set runc env to $PATH.
> Enable detech the runc, judge to download runc or not, and set runc env to $PATH.

- tools/specsValidator/Godeps/Godeps.json
Correct godep.json to enable auto get godeps with specifed revision.
> Correct godep.json to enable auto get godeps with specifed revision.

- tools/specsValidator/README.md
Correct README.md for specsValidator, it can be work proper now.
> Correct README.md for specsValidator, it can be work proper now.

- tools/specsValidator/README.md
Fix bug of godep build to bodep go build .
> Fix bug of godep build to bodep go build .

- tools/specsValidator/README.md
Fix bug in README.md about ./specs to ./specsValidator.
> Fix bug in README.md about ./specs to ./specsValidator.

- tools/specsValidator/containerEnd/README.md
Add containerEnd folder to store the interact programmes in containers.
> Add containerEnd folder to store the interact programmes in containers.

- tools/specsValidator/cases/linuxrlimits/linuxrlimits.go
- tools/specsValidator/cases/linuxrlimits/test_linuxrlimits_RLIMIT_NPROC.go
> modify linux rlimits test case

- tools/specsValidator/Makefile
- tools/specsValidator/README.md
- tools/specsValidator/containerend/Makefile
Update Makfile for main programmes in containerend.
Update README.md for using Makefile.
> Update Makfile and README.md

- tools/specsValidator/adaptor/runc_clean.go
- tools/specsValidator/cases/linuxresources/linuxresoures.go
- tools/specsValidator/cases/linuxresources/test_linuxresources_memory_limit.go
> add cleanrunc function and modify linuxresource testcase

- tools/specsValidator/cases/specprocess/process.go
- tools/specsValidator/utils/bind.go
Add bind.go for set bindfs, preparing going to merge SetBind() and SetRight() in future.
> Add bind.go for set bindfs, preparing going to merge SetBind() and SetRight() in future.

- tools/specsValidator/cases/linuxrootfspropagation/linuxrootpropagation.go
- tools/specsValidator/cases/linuxrootfspropagation/test_linuxrootpropagation.go
- tools/specsValidator/containerend/linuxrootfspropagation.go
> modity linuxrootfspropagation test case to adjust new containerend framwork

- tools/specsValidator/containerend/Makefile
Correct Makefile to auto detect and build the main programmes in containerend
> Correct Makefile to auto detect and build the main programmes in containerend

- tools/specsValidator/cases/specprocess/process.go
- tools/specsValidator/cases/specprocess/test_base.go
- tools/specsValidator/specs.go
Add testcases of testing user for process.
>  Add testcases of testing user for process.

- tools/specsValidator/cases/linuxuidgidmappings/linuxuidgidmappings.go
- tools/specsValidator/cases/linuxuidgidmappings/test_linuxuidgidmappings.go
> add linux uid/gid mapping test case

- tools/specsValidator/cases/linuxcapabilities/linuxcapabilities.go
- tools/specsValidator/cases/linuxcapabilities/test_capabilities_SETFCAP.go
- tools/specsValidator/containerend/linuxcapabilities.go
> adjust linux capabilities test case to new containerend framework

- tools/specsValidator/cases/linuxseccomp/linuxseccomp.go
- tools/specsValidator/cases/linuxseccomp/test_linuxseccomp.go
- tools/specsValidator/containerend/linuxseccomp.go
> add linux seccomp test case

- tools/specsValidator/cases/linuxhooks/linuxhooks.go
- tools/specsValidator/cases/linuxhooks/test_linuxhooks.go
> add linux hooks test case

- tools/specsValidator/cases/specprocess/process.go
- tools/specsValidator/cases/specprocess/test_base.go
- tools/specsValidator/containerend/specprocessenv.go
- tools/specsValidator/report/LinuxSpec.Spec.Process.json
Correct process testcases to output exactly errmsg, and add testcases for test env.
>  Correct process testcases to output exactly errmsg, and add testcases for test env.

- tools/specsValidator/adaptor/runc_clean.go
- tools/specsValidator/cases/linuxapparmorprofile/linuxapparmorprofile.go
- tools/specsValidator/cases/linuxrlimits/linuxrlimits.go
- tools/specsValidator/cases/linuxrootfspropagation/linuxrootpropagation.go
- tools/specsValidator/cases/linuxrootfspropagation/test_linuxrootpropagation.go
- tools/specsValidator/cases/linuxseccomp/linuxseccomp.go
- tools/specsValidator/cases/linuxselinuxlabel/test_linuxseliuxlabel.go
Correct the cases according to intergration test result
> Correct the cases according to intergration test result

- tools/specsValidator/cases/linuxselinuxlabel/linuxselinuxlabel.go
- tools/specsValidator/cases/linuxselinuxlabel/test_linuxseliuxlabel.go
> modify the selinux lable test case

- tools/specsValidator/cases/linuxcapabilities/test_capabilities_SETFCAP.go
- tools/specsValidator/cases/linuxdevices/test_linuxdevices.go
- tools/specsValidator/cases/linuxhooks/linuxhooks.go
- tools/specsValidator/cases/linuxhooks/test_linuxhooks.go
- tools/specsValidator/cases/linuxresources/linuxresoures.go
- tools/specsValidator/cases/linuxresources/test_linuxresources_memory_limit.go
- tools/specsValidator/cases/linuxrootfspropagation/linuxrootpropagation.go
- tools/specsValidator/cases/linuxseccomp/linuxseccomp.go
- tools/specsValidator/cases/linuxseccomp/test_linuxseccomp.go
- tools/specsValidator/cases/linuxselinuxlabel/linuxselinuxlabel.go
- tools/specsValidator/cases/linuxsysctl/linuxsysctl.go
- tools/specsValidator/cases/linuxsysctl/test_linuxsysctl.go
- tools/specsValidator/cases/linuxuidgidmappings/linuxuidgidmappings.go
- tools/specsValidator/cases/linuxuidgidmappings/test_linuxuidgidmappings.go
- tools/specsValidator/cases/specmount/specmount.go
- tools/specsValidator/cases/specmount/test_mount_tmpfs.go
add more detail information of test cases output
> add more detail information of test cases output 

- tools/specsValidator/specs.go
Fix bug of dealing with parameters.
> Fix bug of dealing with parameters.

- tools/specsValidator/specs.go
- tools/specsValidator/utils/configconvert/config_convert_v0.1.1.go
Add func of LinuxRuntimeToConfig and ConfigToLinuxRuntime.
> Add func of LinuxRuntimeToConfig and ConfigToLinuxRuntime.

- tools/specsValidator/adaptor/runc_start_predraft.go
- tools/specsValidator/adaptor/runc_start_v0.1.1.go
Add supporting of new version of runc.
> Add supporting of new version of runc.

- tools/specsValidator/specs_predraft.go
- tools/specsValidator/specs_v0.1.1.go
Add version control of specs.go
> Add version control of specs.go

- tools/specsValidator/cases/specmount/specmount_v0.1.1.go
- tools/specsValidator/cases/specmount/test_mount_v0.1.1.go
- tools/specsValidator/specs_v0.1.1.go
> add v0.1.1 specmount test case

- tools/specsValidator/hostenv/host_runc.go
> Enable to also update specs in Godeps.

- tools/specsValidator/Makefile
Change default config with Makefile to be predraft version , v0.1.1 is not normally yet.
> Change default config with Makefile to be predraft version , v0.1.1 is not normally yet.

- tools/specsValidator/cases/linuxapparmorprofile/linuxapparmorprofile_v0.1.1.go
- tools/specsValidator/cases/linuxapparmorprofile/test_linuxapparmorprofile_v0.1.1.go
> add v0.1.1 linux apparmor test case

- tools/specsValidator/utils/specsinit/minimumlinuxruntimeinit_v0.1.1.go
- tools/specsValidator/utils/specsinit/minimumlinuxspecinit_v0.1.1.go
> Correct specsinit pkg.

- tools/specsValidator/cases/specroot/root_v0.1.1.go
- tools/specsValidator/cases/specroot/test_root_readonly_v0.1.1.go
- tools/specsValidator/specs_v0.1.1.go
Add support of specroot for v0.1.1.
> Add support of specroot for v0.1.1.

- tools/specsValidator/README.md
> Fix bug in README.md.

- tools/specsValidator/cases/linuxcapabilities/linuxcapabilities_v0.1.1.go
- tools/specsValidator/cases/linuxcapabilities/test_capabilities_SETFCAP_v0.1.1.go
> add v0.1.1 test case of linuxcapabilites

- tools/specsValidator/Makefile
> Fix bug of Makefile.

- tools/specsValidator/hostenv/host_runc.go
> Update hostrunc.go to support build tags.

- tools/specsValidator/cases/linuxresources/linuxresoures.go
- tools/specsValidator/cases/linuxresources/linuxresoures_v0.1.1.go
- tools/specsValidator/cases/linuxrootfspropagation/linuxrootpropagation_v0.1.1.go
- tools/specsValidator/cases/linuxrootfspropagation/test_linuxrootpropagation_v0.1.1.go
- tools/specsValidator/cases/linuxseccomp/linuxseccomp_v0.1.1.go
- tools/specsValidator/cases/linuxseccomp/test_linuxseccomp_v0.1.1.go
- tools/specsValidator/cases/linuxselinuxlabel/linuxselinuxlabel_v0.1.1.go
- tools/specsValidator/cases/linuxselinuxlabel/test_linuxseliuxlabel_v0.1.1.go
- tools/specsValidator/cases/linuxsysctl/linuxsysctl_v0.1.1.go
- tools/specsValidator/cases/linuxsysctl/test_linuxsysctl_v0.1.1.go
> add v0.1.1 test cases

- tools/specsValidator/cases/linuxapparmorprofile/linuxapparmorprofile_v0.1.1 (copy).go
- tools/specsValidator/cases/linuxapparmorprofile/linuxapparmorprofile_v0.1.1.go
- tools/specsValidator/cases/linuxapparmorprofile/test_linuxapparmorprofile_v0.1.1 (copy).go
- tools/specsValidator/cases/linuxhooks/test_linuxhooks_v0.1.1.go
- tools/specsValidator/cases/linuxresources/linuxresoures_v0.1.1.go
> modify the linuxresources test case

- tools/specsValidator/hostenv/host_runc.go
- tools/specsValidator/report/LinuxSpec.Linux.ApparmorProfile.json
- tools/specsValidator/report/LinuxSpec.Linux.Capabilities.json
- tools/specsValidator/report/LinuxSpec.Linux.Devices.json
- tools/specsValidator/report/LinuxSpec.Linux.Hooks.json
- tools/specsValidator/report/LinuxSpec.Linux.Namespaces.json
- tools/specsValidator/report/LinuxSpec.Linux.Resources.json
- tools/specsValidator/report/LinuxSpec.Linux.Rlimits.json
- tools/specsValidator/report/LinuxSpec.Linux.SelinuxProcessLabel.json
- tools/specsValidator/report/LinuxSpec.Linux.UidGidMappings.json
- tools/specsValidator/report/LinuxSpec.Spec.Mount.json
- tools/specsValidator/report/LinuxSpec.Spec.Platform.json
- tools/specsValidator/report/LinuxSpec.Spec.Process.json
- tools/specsValidator/report/LinuxSpec.Spec.Root.json
- tools/specsValidator/report/LinuxSpec.Spec.RootfsPropagation.json
- tools/specsValidator/report/linuxspec.json
- tools/specsValidator/specs_v0.1.1.go
> Format output, update result, fix bug of output place.

- tools/specsValidator/README.md
> Update Readme for fixing bug.

- README.md
- tools/specsValidator/README.md
- tools/specsValidator/cases/specmount/specmount_v0.1.1.go
- tools/specsValidator/cases/specmount/test_mount_v0.1.1.go
> adjust the README to be more clearly

- tools/bundleValidator/README.md
> Fix small bug in README.md

- tools/specsValidator/cases/linuxresources/linuxresoures_v0.1.1.go
- tools/specsValidator/cases/linuxresources/test_linuxresources_memory_limit_v0.11.go
> modity linux resources test case

- tools/specsValidator/cases/linuxcgroupspath/linuxcgroupspath_v0.1.1.go
- tools/specsValidator/cases/linuxcgroupspath/test_linuxcgrouppath_v0.1.1.go
> add cgrouppath test case

- tools/oci-convert/manifest
change the manifest demo to improve  readability
> reformat the manifest demo

- tools/specsValidator/cases/linuxresources/linuxresoures_v0.1.1.go
> modify the usage of unmount cgroup subsystem

- tools/runtimeValidator/cases/linuxcgroupspath/linuxcgroupspath_v0.1.1.go
- tools/runtimeValidator/cases/linuxresources/linuxresoures_v0.1.1.go
- tools/runtimeValidator/cases/linuxresources/test_linuxresources_v0.1.1.go
> modify some test suites according to the change of tool's name

- tools/runtimeValidator/Godeps/Godeps.json
- tools/runtimeValidator/conf/runtimevalidator.conf
- tools/runtimeValidator/setting/setting.go
> add config file read and set support

- tools/runtimeValidator/cases/linuxresources/test_linuxresources_v0.1.1.go
> fix the mis-deleted content

- tools/runtimeValidator/bundles/README.md
- tools/runtimeValidator/cases.conf
- tools/runtimeValidator/config/cases.conf
- tools/runtimeValidator/config/config.go
- tools/runtimeValidator/config/config_test.go
- tools/runtimeValidator/main.go
- tools/runtimeValidator/validate.go
Runable version for muti bundles from cases.conf, without using goroutine
> Runable version for muti bundles from cases.conf, without using goroutine

- tools/runtimeValidator/Makefile
- tools/runtimeValidator/cases.conf
- tools/runtimeValidator/main.go
- tools/runtimeValidator/plugins/Makefile
- tools/runtimeValidator/validate.go
> Fix bug: runnable version for non goroutine version.

- tools/runtimeValidator/main.go
> Add go rountine version.

- tools/runtimeValidator/README.md
Add README.md
linzhinan(zen Lin) <linzhinan@huawei.com>
> Add README.md

- tools/runtimeValidator/main.go
- tools/runtimeValidator/validate.go
> Add mutex for generate configs before copy it to different bundles.

- tools/runtimeValidator/factory/runtimetest.go
> Del runc output in nondebug mode

- ROADMAP.md
> Add ROADMAP

- cases.conf
> add device test case

- utils/convert.go
> add utils to generate rkt run parameter automatically

- main.go
> add root user check function

- factory/factory.go
- factory/runcFactory.go
> Add factory for runtimes

- validate.go
> Adapt runc to runcfactory

- README.md
- main.go
> Update usage of README.md and usage in main.go

- factory/rktFactory.go
- plugins/Makefile
- utils/cmd.go
- validate.go
> Add RKT support for oci runtime testing

- factory/factory.go
- factory/rktFactory.go
- utils/cmd.go
> Fix bug of supportting of rkt

- factory/rktFactory.go
> Disable unecessary output of rkt

- README.md
- main.go
> Update StringFlag of command line.

- hostendvalidate/hostendvalidate.go
> add exception handle to fix the bug

- factory/rktFactory.go
> Add error output of rkt

- factory/rktFactory.go
- factory/runcFactory.go
- validate.go
> Format output

- factory/rktFactory.go
> Add support for rkt return code

- utils/file.go
- utils/hooks/poststart.go
- validate.go
> add file utils and hookvalidation related hooks

- factory/rktFactory.go
> Delete not necessary output when test failed

- testunit.go
> edit test unit and open hooks

- factory/factory.go
- factory/rktFactory.go
- factory/runcFactory.go
> Add container id for factory to support stop oper later

- factory/rktFactory.go
- factory/runcFactory.go
> Add init func for factory

- factory/rktFactory.go
- testunit.go
> Add stopRT for rkt after each test

- testunit.go
> Add result and errInfo to TestUnit

- main.go
- testunit.go
> Fix design error with testUnit, fix bug of output: should place after wg.wait()

- factory/runcFactory.go
- main.go
- testunit.go
> Update output of result, and fix bug of Run()

- README.md
- main.go
- testunit.go
> Add ouput support

- testunit.go
> Fix bug of ouput

- factory/rktFactory.go
- factory/runcFactory.go
- testunit.go
> Fix rkt and runc factory bug

- main.go
> Add debug mode to ocitest

- factory/factory.go
- factory/rktFactory.go
- testunit.go
> Correct using oci2aci, delete not necessary codes

- README.md
> Update README.md to add debug option

- testunit.go
> Fix bug to check input cmd of output=

- factory/rktFactory.go
- main.go
- testunit.go
- utils/config/config_test.go
- utils/hooks/poststart.go
> Split long line to ensurce the character of each line less than 100

- testunit.go
> Fix bug when setRuntime

- README.md
> fix link to testflowchart

- main.go
> Fix bug in app cmd explain.

- README.md
> Fix web link err in README.md

- utils/config/config.go
> small fix: remove len used as a variable name

- testunit.go
- utils/config/config.go
> use sepcified cases.conf

- factory/rktFactory.go
> rktFactory: tiny tfix

- factory/dockerFactory.go
- factory/factory.go
- plugins/Makefile
> support docker runtime

- .gitignore
> ignore compiled files
